# Generated by Django 3.0.4 on 2020-04-25 09:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0003_auto_20200425_0835'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(4)])),
                ('password', models.CharField(max_length=16, validators=[django.core.validators.MinLengthValidator(6)])),
                ('verification', models.BooleanField(default=False)),
                ('telephone', models.CharField(max_length=11)),
                ('shopname', models.CharField(max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(4)])),
                ('credit', models.SmallIntegerField(default=100)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='verification',
            field=models.BooleanField(default=False),
        ),
    ]
