# Generated by Django 2.2 on 2020-04-28 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='active',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='created',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='name',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='updated',
        ),
    ]
